### ISSUE TITLE
Rethinking the Definition of "Active Accounts"

### ISSUE THREAD

**Issue by NZT48** [colorfulnotion/substrate-etl#11]
In the current Substrate documentation, the term "Active Accounts" is defined as: 
https://github.com/colorfulnotion/substrate-etl/blob/9f5e01f144a8450200076a854e832f1fa02745a9/DEFINITIONS.md?plain=1#L32

While this definition is generally accurate, it has the unintended consequence of excluding accounts associated with unsigned extrinsics (ie all EVM transactions). This exclusion is significant because it may create an unfair distinction between parachains that have EVM and those that do not.

My suggestion is to follow same approach as Subscan, and to include unsigned extrinsics into this definition.

**Comment by sourabhniyogi** [comment]
Thanks for asking!   I think we will be able to have Active Accounts (EVM) mean

```
Accounts that have signed an transaction on a EVM chain
```

which covers a far bigger use case but haven't put it into effect for the EVM chains in Substrate and should.   Accommodating the Substrate+EVM hybrids will then yield two different numbers.  The "deduping" across Substrate+EVM could be accomodated with linkage between a Substrate and EVM account to yield a 3rd number, if one exists.  The situation with "derivative accounts" within Substrate sort of demands this sort of solution, within Substrate only, where if A' is a derivative account of A, we would only count one for "A" and not double count for A'.  This is the "derivative account" future of Polkadot.

**Comment by sourabhniyogi** [comment]
> In the current Substrate documentation, the term "Active Accounts" is defined as:
> 
> https://github.com/colorfulnotion/substrate-etl/blob/9f5e01f144a8450200076a854e832f1fa02745a9/DEFINITIONS.md?plain=1#L32
> 
> While this definition is generally accurate, it has the unintended consequence of excluding accounts associated with unsigned extrinsics (ie all EVM transactions). This exclusion is significant because it may create an unfair distinction between parachains that have EVM and those that do not.
> 
> My suggestion is to follow same approach as Subscan, and to include unsigned extrinsics into this definition.

We compiled MAU datasets for both Substrate+EVM (including Origin Trail) which are tabulated here:
 https://analytics.polkaholic.io/superset/dashboard/68/
We decided to match (to the best of our knowledge) Etherscan's approach on "Send count"  eg
 https://moonscan.io/chart/active-address
and ended up with numbers that match on moonbeam and presumably origintrail as well.  We'll update substrate-etl docs to describe how you and others can get these hybrid datasets as well as how MAUs/DAUs.  

Thanks for checking in!

**Comment by sourabhniyogi** [comment]
https://forum.polkadot.network/t/substrate-vs-evm-ecosystem-comparison/4454

Let us know if the numbers match up @NZT48 given the Etherscan-like approach we took?
