### ISSUE TITLE
`xcmtransfers` table not found in BigQuery anymore

### ISSUE THREAD

**Issue by raag-bitwave** [colorfulnotion/substrate-etl#16]
Hi, it seems that the `xcmtransfers` table, for both `crypto_polygon` and `crypto_kusama`, doesn't exist anymore on BigQuery. Was this table moved elsewhere or deprecated?
I still see references to it in the READMEs so not sure why I can't find it. Here's a reference query and screenshot
```
SELECT * FROM `bigquery-public-data.crypto_polkadot.xcmtransfers` LIMIT 10;
``` 
<img width="674" alt="image" src="https://github.com/colorfulnotion/substrate-etl/assets/136370008/9b6018b0-877a-4ad5-9c70-d3cd1aa1096e">

**Comment by mkchungs** [comment]
xcmtransfers is currently under maintenance. Availability is impacted at the moment
