### ISSUE TITLE
readme could explain how to use substrate-etl

### ISSUE THREAD

**Issue by jangorecki** [colorfulnotion/substrate-etl#17]
I am interested to extract substrate data into csv files (or duckdb if directly possible).
Readme, as is now, is completely useless as it doesn't touch subject of ETL process.

**Comment by sourabhniyogi** [comment]
https://cloud.google.com/bigquery/docs/exporting-data describes how to export BigQuery datasets into CSV.

https://chat.openai.com/share/854213dc-8525-43be-b223-4fd119eae546 covers how to map CSV into DuckDB.

**Comment by jangorecki** [comment]
And how to do without bigquery? Issue was asking for direct access, so closing as completed does not seem to fit.
